<script>
	import IssueList from "../components/IssueList.svelte";
	import { project } from "../stores/project";

	const issues = [
		{
			id: 5,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 13,
				permissions: { create: true, write: true, read: true },
				name: "Done",
				color: "#3B8C00",
				created_on: "2021-02-16T12:13:53.473675Z",
				order_pos: 4,
				project: 2,
			},
			team: null,
			sub_issues: [
				{
					id: 17,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 13,
						permissions: { create: true, write: true, read: true },
						name: "Done",
						color: "#3B8C00",
						created_on: "2021-02-16T12:13:53.473675Z",
						order_pos: 4,
						project: 2,
					},
					priority: {
						id: 3,
						name: "medium",
						color: "yellow",
						icon: "chevron-up",
					},
					title: "fdsfsdfddsfdfsd",
					description: "",
					created_on: "2021-03-29T16:04:20.836084Z",
					started_on: null,
					due_to: null,
					ownId: 2,
					issue: 5,
				},
				{
					id: 16,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 13,
						permissions: { create: true, write: true, read: true },
						name: "Done",
						color: "#3B8C00",
						created_on: "2021-02-16T12:13:53.473675Z",
						order_pos: 4,
						project: 2,
					},
					priority: {
						id: 1,
						name: "lowest",
						color: "green",
						icon: "chevrons-down",
					},
					title: "fsdfsdf",
					description: "",
					created_on: "2021-03-29T15:58:54.649509Z",
					started_on: null,
					due_to: null,
					ownId: 1,
					issue: 5,
				},
			],
			priority: { id: 4, name: "high", color: "red", icon: "chevrons-up" },
			ownId: 3,
			title: "lkjlk",
			description: "",
			created_on: "2021-02-11T17:35:41.874829Z",
			started_on: "2021-02-16",
			due_to: "2021-02-26",
			order_pos: 0,
			project: 2,
		},
		{
			id: 15,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 4,
				permissions: { create: true, write: true, read: true },
				name: "Todo",
				color: "#004EC1",
				created_on: "2021-02-11T17:33:26.151218Z",
				order_pos: 0,
				project: 2,
			},
			team: null,
			sub_issues: [
				{
					id: 19,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 4,
						permissions: { create: true, write: true, read: true },
						name: "Todo",
						color: "#004EC1",
						created_on: "2021-02-11T17:33:26.151218Z",
						order_pos: 0,
						project: 2,
					},
					priority: null,
					title: "idk",
					description: "",
					created_on: "2021-04-09T10:37:53.284904Z",
					started_on: "2021-04-12",
					due_to: "2021-04-14",
					ownId: 1,
					issue: 15,
				},
			],
			priority: { id: 4, name: "high", color: "red", icon: "chevrons-up" },
			ownId: 6,
			title: "Vshdbshs",
			description: "## daniel\n\n```\nimport a from 'dasd';\n```",
			created_on: "2021-02-13T13:58:08.911981Z",
			started_on: "2021-04-13",
			due_to: "2021-04-23",
			order_pos: 0,
			project: 2,
		},
		{
			id: 30,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 14,
				permissions: { create: true, write: true, read: true },
				name: "Push",
				color: "#AF1111",
				created_on: "2021-02-16T12:16:31.440248Z",
				order_pos: 3,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: null,
			ownId: 8,
			title: "fgdgfd",
			description: "",
			created_on: "2021-02-22T10:15:09.099255Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 31,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 5,
				permissions: { create: true, write: true, read: true },
				name: "In Progress",
				color: "#6554c0",
				created_on: "2021-02-11T17:33:26.157153Z",
				order_pos: 1,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: { id: 4, name: "high", color: "red", icon: "chevrons-up" },
			ownId: 9,
			title: "fgdgfd",
			description: "",
			created_on: "2021-02-22T10:15:09.234046Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 32,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 4,
				permissions: { create: true, write: true, read: true },
				name: "Todo",
				color: "#004EC1",
				created_on: "2021-02-11T17:33:26.151218Z",
				order_pos: 0,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: { id: 2, name: "low", color: "green", icon: "chevron-down" },
			ownId: 10,
			title: "dsad",
			description: "",
			created_on: "2021-02-22T11:55:59.399795Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 66,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: {
				username: "ionut",
				email: "daniel@veelancing.io",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/default.jpg",
					company: "",
					department: "",
					job: "",
				},
				id: 2,
			},
			status: {
				id: 4,
				permissions: { create: true, write: true, read: true },
				name: "Todo",
				color: "#004EC1",
				created_on: "2021-02-11T17:33:26.151218Z",
				order_pos: 0,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: { id: 5, name: "highest", color: "red", icon: "chevrons-up" },
			ownId: 11,
			title: "dada",
			description: "",
			created_on: "2021-03-14T12:51:07.408028Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 67,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 4,
				permissions: { create: true, write: true, read: true },
				name: "Todo",
				color: "#004EC1",
				created_on: "2021-02-11T17:33:26.151218Z",
				order_pos: 0,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: { id: 3, name: "medium", color: "yellow", icon: "chevron-up" },
			ownId: 12,
			title: "Gsgs",
			description: "",
			created_on: "2021-03-14T12:51:17.902511Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 68,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 14,
				permissions: { create: true, write: true, read: true },
				name: "Push",
				color: "#AF1111",
				created_on: "2021-02-16T12:16:31.440248Z",
				order_pos: 3,
				project: 2,
			},
			team: null,
			sub_issues: [],
			priority: { id: 3, name: "medium", color: "yellow", icon: "chevron-up" },
			ownId: 13,
			title: "Dadada",
			description: "",
			created_on: "2021-03-14T13:07:56.764127Z",
			started_on: null,
			due_to: null,
			order_pos: 0,
			project: 2,
		},
		{
			id: 69,
			permissions: { create: true, write: true, read: true },
			reporter: {
				username: "danutu",
				email: "dany89yt@yahoo.com",
				first_name: "Daniel",
				last_name: "Ionut",
				profile: {
					avatar: "http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
					company: "NewApp",
					department: "Full Stack",
					job: "Web Developer",
				},
				id: 1,
			},
			asignee: null,
			status: {
				id: 5,
				permissions: { create: true, write: true, read: true },
				name: "In Progress",
				color: "#6554c0",
				created_on: "2021-02-11T17:33:26.157153Z",
				order_pos: 1,
				project: 2,
			},
			team: {
				id: 10,
				permissions: { create: true, write: true, read: true },
				leader: {
					username: "danutu",
					email: "dany89yt@yahoo.com",
					first_name: "Daniel",
					last_name: "Ionut",
					profile: {
						avatar:
							"http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
						company: "NewApp",
						department: "Full Stack",
						job: "Web Developer",
					},
					id: 1,
				},
				members: [
					{
						username: "danutu",
						email: "dany89yt@yahoo.com",
						first_name: "Daniel",
						last_name: "Ionut",
						profile: {
							avatar:
								"http://localhost/api/media/users/avatars/Danutu_IuYdY39.jpg",
							company: "NewApp",
							department: "Full Stack",
							job: "Web Developer",
						},
						id: 1,
					},
					{
						username: "dany89ytro",
						email: "dany89ytro@gmail.com",
						first_name: "Daniel",
						last_name: "Ionut",
						profile: {
							avatar:
								"http://localhost/api/media/users/avatars/Danutu_K69ejlY.jpg",
							company: "",
							department: "",
							job: "",
						},
						id: 7,
					},
					{
						username: "ionut",
						email: "daniel@veelancing.io",
						first_name: "Daniel",
						last_name: "Ionut",
						profile: {
							avatar: "http://localhost/api/media/users/avatars/default.jpg",
							company: "",
							department: "",
							job: "",
						},
						id: 2,
					},
				],
				name: "Backend",
				project: 2,
			},
			sub_issues: [
				{
					id: 12,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 5,
						permissions: { create: true, write: true, read: true },
						name: "In Progress",
						color: "#6554c0",
						created_on: "2021-02-11T17:33:26.157153Z",
						order_pos: 1,
						project: 2,
					},
					priority: null,
					title: "fdsjlkfjsdkfjs",
					description: "",
					created_on: "2021-03-28T14:55:26.354305Z",
					started_on: null,
					due_to: null,
					ownId: 7,
					issue: 69,
				},
				{
					id: 13,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 5,
						permissions: { create: true, write: true, read: true },
						name: "In Progress",
						color: "#6554c0",
						created_on: "2021-02-11T17:33:26.157153Z",
						order_pos: 1,
						project: 2,
					},
					priority: null,
					title: "gfdgfd",
					description: "",
					created_on: "2021-03-28T15:27:44.226488Z",
					started_on: null,
					due_to: null,
					ownId: 8,
					issue: 69,
				},
				{
					id: 15,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 5,
						permissions: { create: true, write: true, read: true },
						name: "In Progress",
						color: "#6554c0",
						created_on: "2021-02-11T17:33:26.157153Z",
						order_pos: 1,
						project: 2,
					},
					priority: null,
					title: "fsdfsd",
					description: "",
					created_on: "2021-03-28T15:35:02.787891Z",
					started_on: null,
					due_to: null,
					ownId: 10,
					issue: 69,
				},
				{
					id: 10,
					permissions: { create: true, write: true, read: true },
					asignee: {
						username: "ionut",
						email: "daniel@veelancing.io",
						first_name: "Daniel",
						last_name: "Ionut",
						profile: {
							avatar: "http://localhost/api/media/users/avatars/default.jpg",
							company: "",
							department: "",
							job: "",
						},
						id: 2,
					},
					status: {
						id: 14,
						permissions: { create: true, write: true, read: true },
						name: "Push",
						color: "#AF1111",
						created_on: "2021-02-16T12:16:31.440248Z",
						order_pos: 3,
						project: 2,
					},
					priority: { id: 4, name: "high", color: "red", icon: "chevrons-up" },
					title: "jhkjfhskjdf",
					description: "",
					created_on: "2021-03-28T14:55:20.272578Z",
					started_on: null,
					due_to: null,
					ownId: 5,
					issue: 69,
				},
				{
					id: 8,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 19,
						permissions: { create: true, write: true, read: true },
						name: "To Push",
						color: "#436DC1",
						created_on: "2021-03-28T08:39:00.050405Z",
						order_pos: 2,
						project: 2,
					},
					priority: { id: 4, name: "high", color: "red", icon: "chevrons-up" },
					title: "jhfksdhfs",
					description: "",
					created_on: "2021-03-28T14:42:27.154480Z",
					started_on: null,
					due_to: null,
					ownId: 4,
					issue: 69,
				},
				{
					id: 7,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 5,
						permissions: { create: true, write: true, read: true },
						name: "In Progress",
						color: "#6554c0",
						created_on: "2021-02-11T17:33:26.157153Z",
						order_pos: 1,
						project: 2,
					},
					priority: {
						id: 1,
						name: "lowest",
						color: "green",
						icon: "chevrons-down",
					},
					title: "hhfjsdhf",
					description: "",
					created_on: "2021-03-28T14:41:56.956806Z",
					started_on: "2021-04-12",
					due_to: "2021-04-16",
					ownId: 3,
					issue: 69,
				},
				{
					id: 11,
					permissions: { create: true, write: true, read: true },
					asignee: null,
					status: {
						id: 13,
						permissions: { create: true, write: true, read: true },
						name: "Done",
						color: "#3B8C00",
						created_on: "2021-02-16T12:13:53.473675Z",
						order_pos: 4,
						project: 2,
					},
					priority: {
						id: 3,
						name: "medium",
						color: "yellow",
						icon: "chevron-up",
					},
					title: "ufldsjfkls",
					description: "",
					created_on: "2021-03-28T14:55:23.273030Z",
					started_on: null,
					due_to: null,
					ownId: 6,
					issue: 69,
				},
			],
			priority: {
				id: 1,
				name: "lowest",
				color: "green",
				icon: "chevrons-down",
			},
			ownId: 14,
			title: "Api Gateway",
			description: "",
			created_on: "2021-03-24T08:19:02.141921Z",
			started_on: "2021-04-15",
			due_to: "2021-04-19",
			order_pos: 0,
			project: 2,
		},
	];
</script>

<div class="header">
	<img src={$project.icon} alt={$project.name} height="18px" width="18px" />
	<span>{$project.name}</span>
	<select />
</div>
<hr />
<IssueList {issues} />

<style>
	.header {
		display: flex;
		flex-flow: row;
		padding: 0.2rem 0;
	}

	.header img {
		border-radius: 3px;
	}

	.header span {
		margin-left: 0.3rem;
		font-size: 13px;
	}

	hr {
		border-color: var(--vscode-textLink-foreground);
		width: 100%;
	}
</style>
